env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  indent: ["warn", 2]
  no-unused-vars: 1
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore_dangle: ["error" { "allow": ["__filename", "__dirname"] }]