name: linter-tests-run

on: 
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  linter-tests-check:
    name: Linter and Tests check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: make install

      - name: Run a linter
        run: make lint

      - name: Run tests
        run: make test